Question 1: Array Dimensions
The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

Number of dimensions in sales_data
Shape of sales_data
Total number of values
Data type of the array
Memory occupied by the array

In [ ]:
print("Number of dimensions:", sales_data.ndim
print("Shape of sales_data:", sales_data.shape)

print("Total number of elements:", sales_data.size)

print("Data type:", sales_data.dtype)
print("Memory occupied (in bytes):", sales_data.nbytes)
Number of dimensionsin sample_data: 2
Shape of sales_data: (5, 6)
Total number of elements in sales_data: 30
Data typeof sample_data: int64
Memory occupied by sales_data: 240bytes
      512

Question 2: Store and Category Count
Calculate the following:

Total number of stores
Total number of product categories
Total number of store-category combinations

Question 2: Store and Category Count
Calculate the following:

Total number of stores
Total number of product categories
Total number of store-category combinations

In [ ]:
print("Total number of stores:", total_stores)
print("Total number of product categories:", total_categories)
print("Total number of store-category combinations:", store_category_combinations)

  total number of stores: 5
  total number of product categories: 6
  total number of store-category combinations: 30

Question 3: Sales Data Type Conversion
The reporting application requires sales values in floating-point format.

Convert sales_data into:

float32
float64
Compare the memory used by both arrays.

In [ ]:
import numpy as np

sales_data = np.array([100, 250, 175, 300, 450])
sales_float32 = sales_data.astype(np.float32)

sales_float64 = sales_data.astype(np.float64)

print("Data type (float32):", sales_float32.dtype)
print("Data type (float64):", sales_float64.dtype)

print("Memory used by float32 array:", sales_float32.nbytes, "bytes")
print("Memory used by float64 array:", sales_float64.nbytes, "bytes")

Data type (float32): float32
Data type (float64): float64
Memory used by float32 array: 20 bytes
Memory used by float64 array: 40 bytes


Part 3: Indexing and Data Extraction
Question 4: Bengaluru Store Analysis
The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.



In [ ]:
import numpy as np

stores = np.array(["Chennai", "Bengaluru", "Hyderabad", "Mumbai"])

index = np.where(stores == "Bengaluru")[0][0]

print("Sales data for Bengaluru:")
print(sales_data[index])

Sales data for Bengaluru:
250


Question 5: Mumbai Cost Analysis
Extract the total cost incurred by the Mumbai store for all product categories.



In [ ]:
import numpy as np
cost_data = np.array([
    [25000,22000,20000,24000],
    [27000,23000,21000,25000],
    [30000,26000,24000,28000],
    [32000,28000,25000,30000]
])
# Extract Mumbai store cost row (assuming Mumbai is at index 3)
mumbai_cost = cost_data[3]

# Calculate total cost incurred by Mumbai store
total_mumbai_cost = np.sum(mumbai_cost)

# Display the result
print("Cost data for Mumbai:")
print(mumbai_cost)

print("Total cost incurred by Mumbai store:", total_mumbai_cost)

Cost data for Mumbai:
[32000 28000 25000 30000]
Total cost incurred by Mumbai store: 115000


Question 6: Electronics Sales Across Stores
The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from sales_data.

In [ ]:
import numpy as np
sales_data = np.array([
    [100,200,300,],
     [150,250,350],
    [120,220,320]
])
electronics_sales = sales_data[:, 0]

print("Electronics sales across all stores:")
print(electronics_sales)

Electronics sales across all stores:
[100 150 120]


Question 7: Clothing Cost Across Stores
Extract the Clothing cost for every store from cost_data.

In [ ]:
import numpy as np
cost_data =np.array([
    [25000,20000,18000,22000],
    [27000,22000,20000,24000],
    [30000, 25000,22000,26000]
])

clothing_cost = cost_data[:, 1]
print("Clothing cost across all stores:")
print(clothing_cost)

Clothing cost across all stores:
[20000 22000 25000]


Question 8: Hyderabad Furniture Performance
Find the following for Hyderabad:

Furniture sales
Furniture cost
Furniture profit

In [ ]:
import numpy as np

# Assuming Hyderabad is the 3rd store (index 2)
# Assuming Furniture is the 3rd product category (index 2)

# Extract Furniture sales for Hyderabad
hyderabad_furniture_sales = sales_data[2, 2]

# Extract Furniture cost for Hyderabad
hyderabad_furniture_cost = cost_data[2, 2]

# Calculate Furniture profit
hyderabad_furniture_profit = hyderabad_furniture_sales - hyderabad_furniture_cost

# Display results
print("Hyderabad Furniture Sales:", hyderabad_furniture_sales)
print("Hyderabad Furniture Cost:", hyderabad_furniture_cost)
print("Hyderabad Furniture Profit:", hyderabad_furniture_profit)

Hyderabad Furniture Sales: 320
Hyderabad Furniture Cost: 22000
Hyderabad Furniture Profit: -21680


Question 9: Chennai Category Range
Extract Chennai’s sales for the following categories:

Groceries
Clothing
Furniture
Use array slicing.

In [ ]:
import numpy as np
sales_data =np.array([
    [100, 200,300,400],
    [150,250,350,450],
    [250,350,450,550],
    [120,220,320,420]
])

chennai_categories = sales_data[0, 1:4]

print("Chennai sales for Groceries, Clothing, and Furniture:")
print(chennai_categories)

Chennai sales for Groceries, Clothing, and Furniture:
[200 300 400]


Question 10: Selected Store Analysis
Extract sales data for:

Bengaluru
Chennai
Pune
Include only:

Electronics
Clothing
Beauty
Use advanced indexing.

In [ ]:
sales_data = np.array([
    [50000, 40000, 35000, 30000],
    [45000, 38000, 32000, 28000],
    [60000, 42000, 36000, 31000],
    [55000, 39000, 34000, 29000],
    [70000, 45000, 40000, 35000]
])

selected_data = sales_data[[1,0,4]][:, [1,2,3]]
bengaluru,chennai,pune = sales_data[0, 1:4]

print("selected sales data:")
print(selected_data)

selected sales data:
[[38000 32000 28000]
 [40000 35000 30000]
 [45000 40000 35000]]


Part 4: Sales Aggregation
Question 11: Company-Wide Sales
Calculate the total sales revenue generated by all stores and all categories.

In [ ]:
import numpy as np
sales_data = np.array([
    [50000, 40000, 35000, 30000],  # Chennai
    [45000, 38000, 32000, 28000],  # Bengaluru
    [60000, 42000, 36000, 31000],  # Hyderabad
    [55000, 39000, 34000, 29000],  # Mumbai
    [70000, 45000, 40000, 35000]   # Delhi
])
total_sales = np.sum(sales_data)
print("Total sales revenue generated by all stores and categories:", total_sales)

Total sales revenue generated by all stores and categories: 814000


Question 12: Store-Wise Sales
Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format:

Bengaluru: total sales
Hyderabad: total sales
Chennai: total sales
Mumbai: total sales
Pune: total sales

In [ ]:
import numpy as np
store_names = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])
store_total_sales = np.sum(sales_data, axis=1)
for store, total in zip(store_names, store_total_sales):
    print(store + ":", total)

Bengaluru: 155000
Hyderabad: 143000
Chennai: 169000
Mumbai: 157000
Pune: 190000


Question 13: Category-Wise Sales
Calculate total sales for each product category across all stores.

Display each category name with its total sales.

In [ ]:


  import numpy as np
category_names = np.array([
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty"
])
sales_data = np.array([
    [50000,40000,35000,30000],
])
category_total_sales = np.sum(sales_data, axis=0)
for category, total in zip(category_names, category_total_sales):
    print(category + ":", total)







Groceries: 50000
Clothing: 40000
Furniture: 35000
Beauty: 30000


Question 14: Average Sales Per Store
Calculate the average sales generated by each store across all six product categories.



In [ ]:
import numpy as np
sales_data =np.array([
    [85000,42000,31000,27000,32000,78000],
    [45000,25000,35000,55000,45000,35000],
    [10000,34000,56000,45000,40000,34000]
])
categories = np.array([
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Electronics",
    "Sports"
])
average_sales_per_store = np.mean(sales_data, axis=1)
for store, average in enumerate(average_sales_per_store):
    print("Store", store + 1, ":", average)

Store 1 : 49166.666666666664
Store 2 : 40000.0
Store 3 : 36500.0


Question 15: Average Sales Per Category
Calculate the average sales of each product category across the five stores.



In [ ]:
import numpy as np
sales_data =np.array([
    [85000,56000,78000],
    [34000,45000,56000]
])
categories =np,array([
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Electronics"
])
sales_data.groupby('category_name')['sales'].mean()

sales_data.groupby('category')['sales'].mean()

NameError: name 'array' is not defined

Question 16: Highest-Selling Store
Identify:

Index of the store with the highest total sales
Name of the store
Total sales generated by that store
Use np.argmax().

In [ ]:
import numpy as np

def main():
    stores = np.array([
        "Bengaluru",
        "Hyderabad",
        "Chennai",
        "Mumbai"
    ])

    total_sales = np.array([120, 150, 100, 180])
    print(total_sales)

main()

[120 150 100 180]


Question 17: Lowest-Selling Store
Identify the store with the lowest overall sales.

Use np.argmin().

In [ ]:
import numpy as np

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai"
])

total_sales = np.array([120, 150, 100, 180])

lowest_index = np.argmin(total_sales)
lowest_store = stores[lowest_index]

print("Lowest-selling store:", lowest_store)
print("Sales:", total_sales[lowest_index])

Lowest-selling store: Chennai
Sales: 100


Question 18: Highest-Selling Category
Find the product category that generated the highest total sales across the company.



In [ ]:
import numpy as np

categories = np.array([
    "Electronics",
    "Clothing",
    "Groceries",
    "Furniture"
])

category_sales = np.array([450, 320, 600, 280])

highest_index = np.argmax(category_sales)

print("Highest-selling category:", categories[highest_index])
print("Total sales:", category_sales[highest_index])

Highest-selling category: Groceries
Total sales: 600


Question 19: Lowest-Selling Category
Find the product category with the lowest total sales across all stores.



In [ ]:
import numpy as np

categories = np.array([
    "Electronics",
    "Clothing",
    "Groceries",
    "Furniture"
])

category_sales = np.array([450, 320, 600, 280])

lowest_index = np.argmin(category_sales)

print("Lowest-selling category:", categories[lowest_index])
print("Total sales:", category_sales[lowest_index])

Lowest-selling category: Furniture
Total sales: 280


Part 5: Cost Analysis
Question 20: Total Company Cost
Calculate the total cost incurred by SmartMart across all stores and product categories.

In [ ]:
import numpy as np

cost = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

total_company_cost = np.sum(cost)

print("Total Company Cost:", total_company_cost)

Total Company Cost: 1160


Question 21: Store-Wise Cost
Calculate the total cost incurred by each store.

In [ ]:
import numpy as np

cost = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai"
])

store_wise_cost = np.sum(cost, axis=1)

print("Store-Wise Cost:")
for i in range(len(stores)):
    print(stores[i], ":", store_wise_cost[i])

Store-Wise Cost:
Bengaluru : 260
Hyderabad : 285
Chennai : 295
Mumbai : 320


Question 22: Category-Wise Cost
Calculate the total cost incurred for each product category across all stores.

In [ ]:
import numpy as np

cost = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

categories = np.array([
    "Electronics",
    "Clothing",
    "Groceries",
    "Furniture"
])

category_wise_cost = np.sum(cost, axis=0)

print("Category-Wise Cost:")
for i in range(len(categories)):
    print(categories[i], ":", category_wise_cost[i])

Category-Wise Cost:
Electronics : 350
Clothing : 270
Groceries : 230
Furniture : 310


Question 23: Most Expensive Store
Identify the store with the highest total operating cost.

In [ ]:
import numpy as np

cost = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai"
])

store_wise_cost = np.sum(cost, axis=1)

highest_cost_index = np.argmax(store_wise_cost)

print("Most Expensive Store:", stores[highest_cost_index])
print("Total Operating Cost:", store_wise_cost[highest_cost_index])

Most Expensive Store: Mumbai
Total Operating Cost: 320


Question 24: Lowest-Cost Store
Identify the store with the lowest total cost.

In [ ]:
import numpy as np

cost = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai"
])

store_wise_cost = np.sum(cost, axis=1)

lowest_cost_index = np.argmin(store_wise_cost)

print("Lowest-Cost Store:", stores[lowest_cost_index])
print("Total Cost:", store_wise_cost[lowest_cost_index])

Lowest-Cost Store: Bengaluru
Total Cost: 260


Question 25: Most Expensive Product Category
Determine which product category has the highest total cost across all stores.

In [ ]:
import numpy as np

cost = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

categories = np.array([
    "Electronics",
    "Clothing",
    "Groceries",
    "Furniture"
])

category_wise_cost = np.sum(cost, axis=0)

highest_cost_index = np.argmax(category_wise_cost)

print("Most Expensive Product Category:", categories[highest_cost_index])
print("Total Cost:", category_wise_cost[highest_cost_index])

Most Expensive Product Category: Electronics
Total Cost: 350


Part 6: Profit Analysis Using Two Arrays
Question 26: Profit Matrix
Calculate the profit generated for every store and product category.

Use:

profit_data = sales_data - cost_data
Display the complete profit matrix.

In [ ]:
import numpy as np

sales_data = np.array([
    [200, 150, 180, 220],
    [250, 170, 200, 240],
    [180, 160, 190, 210],
    [300, 200, 220, 260]
])

cost_data = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

profit_data = sales_data - cost_data

print("Profit Matrix:")
print(profit_data)

Profit Matrix:
[[120  90 130 150]
 [160 105 145 165]
 [ 95  90 130 130]
 [205 125 155 175]]


Question 27: Store-Wise Profit
Calculate the total profit generated by each store.

In [ ]:
import numpy as np

sales_data = np.array([
    [200, 150, 180, 220],
    [250, 170, 200, 240],
    [180, 160, 190, 210],
    [300, 200, 220, 260]
])

cost_data = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai"
])

profit_data = sales_data - cost_data

store_wise_profit = np.sum(profit_data, axis=1)

print("Store-Wise Profit:")
for i in range(len(stores)):
    print(stores[i], ":", store_wise_profit[i])

Store-Wise Profit:
Bengaluru : 490
Hyderabad : 575
Chennai : 445
Mumbai : 660


Question 28: Category-Wise Profit
Calculate the total profit generated by each product category.

In [ ]:
import numpy as np

sales_data = np.array([
    [200, 150, 180, 220],
    [250, 170, 200, 240],
    [180, 160, 190, 210],
    [300, 200, 220, 260]
])

cost_data = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

categories = np.array([
    "Electronics",
    "Clothing",
    "Groceries",
    "Furniture"
])

profit_data = sales_data - cost_data

category_wise_profit = np.sum(profit_data, axis=0)

print("Category-Wise Profit:")
for i in range(len(categories)):
    print(categories[i], ":", category_wise_profit[i])

Category-Wise Profit:
Electronics : 580
Clothing : 410
Groceries : 560
Furniture : 620


Question 29: Most Profitable Store
Identify the store that generated the highest total profit.

Display:

Store name
Total sales
Total cost
Total profit

In [ ]:
import numpy as np

sales_data = np.array([
    [200, 150, 180, 220],
    [250, 170, 200, 240],
    [180, 160, 190, 210],
    [300, 200, 220, 260]
])

cost_data = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai"
])

profit_data = sales_data - cost_data

store_total_sales = np.sum(sales_data, axis=1)
store_total_cost = np.sum(cost_data, axis=1)
store_total_profit = np.sum(profit_data, axis=1)

most_profitable_index = np.argmax(store_total_profit)

print("Most Profitable Store:", stores[most_profitable_index])
print("Total Sales:", store_total_sales[most_profitable_index])
print("Total Cost:", store_total_cost[most_profitable_index])
print("Total Profit:", store_total_profit[most_profitable_index])

Most Profitable Store: Mumbai
Total Sales: 980
Total Cost: 320
Total Profit: 660


Question 30: Least Profitable Store
Identify the store that generated the lowest total profit.

In [ ]:
import numpy as np

sales_data = np.array([
    [200, 150, 180, 220],
    [250, 170, 200, 240],
    [180, 160, 190, 210],
    [300, 200, 220, 260]
])

cost_data = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai"
])

profit_data = sales_data - cost_data

store_total_profit = np.sum(profit_data, axis=1)

least_profitable_index = np.argmin(store_total_profit)

print("Least Profitable Store:", stores[least_profitable_index])
print("Total Profit:", store_total_profit[least_profitable_index])

Least Profitable Store: Chennai
Total Profit: 445


Question 31: Most Profitable Category
Find the category with the highest total profit across all stores.

In [ ]:
import numpy as np

sales_data = np.array([
    [200, 150, 180, 220],
    [250, 170, 200, 240],
    [180, 160, 190, 210],
    [300, 200, 220, 260]
])

cost_data = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

categories = np.array([
    "Electronics",
    "Clothing",
    "Groceries",
    "Furniture"
])

profit_data = sales_data - cost_data

category_total_profit = np.sum(profit_data, axis=0)

most_profitable_index = np.argmax(category_total_profit)

print("Most Profitable Category:", categories[most_profitable_index])
print("Total Profit:", category_total_profit[most_profitable_index])

Most Profitable Category: Furniture
Total Profit: 620


Question 32: Least Profitable Category
Find the category with the lowest total profit.

In [ ]:
import numpy as np

sales_data = np.array([
    [200, 150, 180, 220],
    [250, 170, 200, 240],
    [180, 160, 190, 210],
    [300, 200, 220, 260]
])

cost_data = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

categories = np.array([
    "Electronics",
    "Clothing",
    "Groceries",
    "Furniture"
])

profit_data = sales_data - cost_data

category_total_profit = np.sum(profit_data, axis=0)

least_profitable_index = np.argmin(category_total_profit)

print("Least Profitable Category:", categories[least_profitable_index])
print("Total Profit:", category_total_profit[least_profitable_index])

Least Profitable Category: Clothing
Total Profit: 410


Question 33: Maximum Individual Profit
Find the highest profit generated by any single store-category combination.

Display:

Profit amount
Store name
Product category
Use np.unravel_index().

In [ ]:
import numpy as np

sales_data = np.array([
    [200, 150, 180, 220],
    [250, 170, 200, 240],
    [180, 160, 190, 210],
    [300, 200, 220, 260]
])

cost_data = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai"
])

categories = np.array([
    "Electronics",
    "Clothing",
    "Groceries",
    "Furniture"
])

profit_data = sales_data - cost_data

max_profit_index = np.argmax(profit_data)

store_index, category_index = np.unravel_index(
    max_profit_index, profit_data.shape
)

print("Maximum Individual Profit:", profit_data[store_index, category_index])
print("Store Name:", stores[store_index])
print("Product Category:", categories[category_index])

Maximum Individual Profit: 205
Store Name: Mumbai
Product Category: Electronics


Question 34: Minimum Individual Profit
Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

In [ ]:
import numpy as np

sales_data = np.array([
    [200, 150, 180, 220],
    [250, 170, 200, 240],
    [180, 160, 190, 210],
    [300, 200, 220, 260]
])

cost_data = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai"
])

categories = np.array([
    "Electronics",
    "Clothing",
    "Groceries",
    "Furniture"
])

profit_data = sales_data - cost_data

min_profit_index = np.argmin(profit_data)

store_index, category_index = np.unravel_index(
    min_profit_index, profit_data.shape
)

print("Minimum Individual Profit:", profit_data[store_index, category_index])
print("Store Name:", stores[store_index])
print("Product Category:", categories[category_index])

Minimum Individual Profit: 90
Store Name: Bengaluru
Product Category: Clothing


Part 7: Profit Margin Analysis
Question 35: Profit Margin Matrix
Calculate the profit margin percentage for every store-category combination.

Use:

profit_margin = (profit_data / sales_data) * 100
Round the result to two decimal places.

In [ ]:
import numpy as np

sales_data = np.array([
    [200, 150, 180, 220],
    [250, 170, 200, 240],
    [180, 160, 190, 210],
    [300, 200, 220, 260]
])

cost_data = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

profit_data = sales_data - cost_data

profit_margin = (profit_data / sales_data) * 100

profit_margin = np.round(profit_margin, 2)

print("Profit Margin Matrix (%):")
print(profit_margin)

Profit Margin Matrix (%):
[[60.   60.   72.22 68.18]
 [64.   61.76 72.5  68.75]
 [52.78 56.25 68.42 61.9 ]
 [68.33 62.5  70.45 67.31]]


Question 36: Store-Wise Profit Margin
Calculate the overall profit margin percentage for each store using:

Store Profit Margin =
Total Store Profit / Total Store Sales × 100

In [ ]:
import numpy as np

sales_data = np.array([
    [200, 150, 180, 220],
    [250, 170, 200, 240],
    [180, 160, 190, 210],
    [300, 200, 220, 260]
])

cost_data = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai"
])

profit_data = sales_data - cost_data

total_store_sales = np.sum(sales_data, axis=1)
total_store_profit = np.sum(profit_data, axis=1)

store_profit_margin = (total_store_profit / total_store_sales) * 100

store_profit_margin = np.round(store_profit_margin, 2)

print("Store-Wise Profit Margin:")
for i in range(len(stores)):
    print(stores[i], ":", store_profit_margin[i], "%")

Store-Wise Profit Margin:
Bengaluru : 65.33 %
Hyderabad : 66.86 %
Chennai : 60.14 %
Mumbai : 67.35 %


Question 37: Category-Wise Profit Margin
Calculate the overall profit margin percentage for each product category.

In [ ]:
import numpy as np

sales_data = np.array([
    [200, 150, 180, 220],
    [250, 170, 200, 240],
    [180, 160, 190, 210],
    [300, 200, 220, 260]
])

cost_data = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

categories = np.array([
    "Electronics",
    "Clothing",
    "Groceries",
    "Furniture"
])

profit_data = sales_data - cost_data

total_category_sales = np.sum(sales_data, axis=0)
total_category_profit = np.sum(profit_data, axis=0)

category_profit_margin = (total_category_profit / total_category_sales) * 100

category_profit_margin = np.round(category_profit_margin, 2)

print("Category-Wise Profit Margin:")
for i in range(len(categories)):
    print(categories[i], ":", category_profit_margin[i], "%")

Category-Wise Profit Margin:
Electronics : 62.37 %
Clothing : 60.29 %
Groceries : 70.89 %
Furniture : 66.67 %


Question 38: Best Store by Profit Margin
Identify the store with the highest overall profit margin.

In [ ]:
import numpy as np

sales_data = np.array([
    [200, 150, 180, 220],
    [250, 170, 200, 240],
    [180, 160, 190, 210],
    [300, 200, 220, 260]
])

cost_data = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai"
])

profit_data = sales_data - cost_data

total_store_sales = np.sum(sales_data, axis=1)
total_store_profit = np.sum(profit_data, axis=1)

store_profit_margin = (total_store_profit / total_store_sales) * 100
store_profit_margin = np.round(store_profit_margin, 2)

best_store_index = np.argmax(store_profit_margin)

print("Best Store by Profit Margin:", stores[best_store_index])
print("Profit Margin:", store_profit_margin[best_store_index], "%")

Best Store by Profit Margin: Mumbai
Profit Margin: 67.35 %


Question 39: Best Category by Profit Margin
Identify the product category with the highest profit margin.

In [ ]:
import numpy as np

sales_data = np.array([
    [200, 150, 180, 220],
    [250, 170, 200, 240],
    [180, 160, 190, 210],
    [300, 200, 220, 260]
])

cost_data = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

categories = np.array([
    "Electronics",
    "Clothing",
    "Groceries",
    "Furniture"
])

profit_data = sales_data - cost_data

total_category_sales = np.sum(sales_data, axis=0)
total_category_profit = np.sum(profit_data, axis=0)

category_profit_margin = (total_category_profit / total_category_sales) * 100
category_profit_margin = np.round(category_profit_margin, 2)

best_category_index = np.argmax(category_profit_margin)

print("Best Category by Profit Margin:", categories[best_category_index])
print("Profit Margin:", category_profit_margin[best_category_index], "%")

Best Category by Profit Margin: Groceries
Profit Margin: 70.89 %


Question 40: Low-Margin Transactions
Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

Store
Category
Sales
Cost
Profit
Profit margin
Use Boolean indexing.

In [ ]:
import numpy as np

sales_data = np.array([
    [200, 150, 180, 220],
    [250, 170, 200, 240],
    [180, 160, 190, 210],
    [300, 200, 220, 260]
])

cost_data = np.array([
    [80, 60, 50, 70],
    [90, 65, 55, 75],
    [85, 70, 60, 80],
    [95, 75, 65, 85]
])

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai"
])

categories = np.array([
    "Electronics",
    "Clothing",
    "Groceries",
    "Furniture"
])

profit_data = sales_data - cost_data

profit_margin = (profit_data / sales_data) * 100
profit_margin = np.round(profit_margin, 2)

low_margin = profit_margin < 22

store_index, category_index = np.where(low_margin)

print("Low-Margin Transactions:")
for i in range(len(store_index)):
    s = store_index[i]
    c = category_index[i]

    print("Store:", stores[s])
    print("Category:", categories[c])
    print("Sales:", sales_data[s, c])
    print("Cost:", cost_data[s, c])
    print("Profit:", profit_data[s, c])
    print("Profit Margin:", profit_margin[s, c], "%")
    print("----------------------")

Low-Margin Transactions:


Part 8: Boolean Filtering
Question 41: High Sales Values
Find all sales values greater than ₹5,00,000.

In [ ]:
import numpy as np

sales_data = np.array([
    [200000, 150000, 180000, 220000],
    [250000, 170000, 200000, 540000],
    [180000, 160000, 190000, 210000],
    [600000, 200000, 220000, 260000]
])

# Boolean condition
high_sales = sales_data > 500000

# Extract values
high_sales_values = sales_data[high_sales]

print("Sales values greater than ₹5,00,000:")
print(high_sales_values)

Sales values greater than ₹5,00,000:
[540000 600000]


Question 42: Low Sales Values
Find all sales values below ₹2,00,000.

In [ ]:
import numpy as np

sales_data = np.array([
    [200000, 150000, 180000, 220000],
    [250000, 170000, 200000, 540000],
    [180000, 160000, 190000, 210000],
    [600000, 200000, 220000, 260000]
])

# Boolean condition
low_sales = sales_data < 200000

# Extract values
low_sales_values = sales_data[low_sales]

print("Sales values below ₹2,00,000:")
print(low_sales_values)

Sales values below ₹2,00,000:
[150000 180000 170000 180000 160000 190000]


Question 43: High Profit Values
Find all store-category combinations where profit is greater than ₹1,50,000.



In [ ]:
import numpy as np

sales_data = np.array([
    [200000, 150000, 180000, 220000],
    [250000, 170000, 200000, 240000],
    [180000, 160000, 190000, 210000],
    [300000, 200000, 220000, 260000]
])

cost_data = np.array([
    [80000, 60000, 50000, 70000],
    [90000, 65000, 55000, 75000],
    [85000, 70000, 60000, 80000],
    [95000, 75000, 65000, 85000]
])

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai"
])

categories = np.array([
    "Electronics",
    "Clothing",
    "Groceries",
    "Furniture"
])

profit_data = sales_data - cost_data

# Boolean indexing condition
high_profit = profit_data > 150000

# Find positions
store_index, category_index = np.where(high_profit)

print("High Profit Store-Category Combinations:")

for i in range(len(store_index)):
    s = store_index[i]
    c = category_index[i]

    print("Store:", stores[s])
    print("Category:", categories[c])
    print("Profit:", profit_data[s, c])
    print("----------------------")

High Profit Store-Category Combinations:
Store: Hyderabad
Category: Electronics
Profit: 160000
----------------------
Store: Hyderabad
Category: Furniture
Profit: 165000
----------------------
Store: Mumbai
Category: Electronics
Profit: 205000
----------------------
Store: Mumbai
Category: Groceries
Profit: 155000
----------------------
Store: Mumbai
Category: Furniture
Profit: 175000
----------------------


Question 44: Moderate Sales Range
Find sales values between ₹2,50,000 and ₹5,00,000.

Use np.logical_and().

In [ ]:
import numpy as np

sales_data = np.array([
    [200000, 150000, 180000, 220000],
    [250000, 170000, 200000, 540000],
    [180000, 160000, 190000, 210000],
    [600000, 200000, 220000, 260000]
])

# Boolean condition using np.logical_and()
moderate_sales = np.logical_and(
    sales_data >= 250000,
    sales_data <= 500000
)

# Extract values
moderate_sales_values = sales_data[moderate_sales]

print("Sales values between ₹2,50,000 and ₹5,00,000:")
print(moderate_sales_values)

Sales values between ₹2,50,000 and ₹5,00,000:
[250000 260000]


Question 45: Premium Performance
A store-category combination is considered premium when:

Sales are greater than ₹5,00,000
Profit is greater than ₹1,50,000
Find all premium-performing combinations.

In [ ]:
import numpy as np

sales_data = np.array([
    [200000, 150000, 180000, 220000],
    [250000, 170000, 200000, 540000],
    [180000, 160000, 190000, 210000],
    [600000, 200000, 220000, 260000]
])

cost_data = np.array([
    [80000, 60000, 50000, 70000],
    [90000, 65000, 55000, 75000],
    [85000, 70000, 60000, 80000],
    [95000, 75000, 65000, 85000]
])

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai"
])

categories = np.array([
    "Electronics",
    "Clothing",
    "Groceries",
    "Furniture"
])

profit_data = sales_data - cost_data

# Premium condition
premium = np.logical_and(
    sales_data > 500000,
    profit_data > 150000
)

# Find positions
store_index, category_index = np.where(premium)

print("Premium Performing Store-Category Combinations:")

for i in range(len(store_index)):
    s = store_index[i]
    c = category_index[i]

    print("Store:", stores[s])
    print("Category:", categories[c])
    print("Sales:", sales_data[s, c])
    print("Profit:", profit_data[s, c])
    print("----------------------")

Premium Performing Store-Category Combinations:
Store: Hyderabad
Category: Furniture
Sales: 540000
Profit: 465000
----------------------
Store: Mumbai
Category: Electronics
Sales: 600000
Profit: 505000
----------------------


Question 46: Underperforming Combinations
A store-category combination is considered underperforming when:

Sales are below ₹2,50,000
Profit margin is below 25%
Find all such combinations.

In [ ]:
profit_data = sales_data - cost_data

# Calculate profit margin
profit_margin = (profit_data / sales_data) * 100
profit_margin = np.round(profit_margin, 2)

# Underperforming condition
underperforming = np.logical_and(
    sales_data < 250000,
    profit_margin < 25
)

# Find positions
store_index, category_index = np.where(underperforming)

print("Underperforming Store-Category Combinations:")

for i in range(len(store_index)):
    s = store_index[i]
    c = category_index[i]

    print("Store:", stores[s])
    print("Category:", categories[c])
    print("Sales:", sales_data[s, c])
    print("Profit:", profit_data[s, c])
    print("Profit Margin:", profit_margin[s, c], "%")
    print("----------------------")

Underperforming Store-Category Combinations:


Question 47: Category Performance Classification
Create a new array that classifies every sales value as:

"High" when sales are at least ₹5,00,000
"Medium" when sales are between ₹2,50,000 and ₹4,99,999
"Low" when sales are below ₹2,50,000
Use np.where() or np.select().



In [ ]:
import numpy as np

sales_data = np.array([
    [200000, 150000, 180000, 220000],
    [250000, 170000, 200000, 540000],
    [180000, 160000, 190000, 210000],
    [600000, 200000, 220000, 260000]
])

sales_classification = np.where(
    sales_data >= 500000, "High",
    np.where(sales_data >= 250000, "Medium", "Low")
)

print(sales_classification)

[['Low' 'Low' 'Low' 'Low']
 ['Medium' 'Low' 'Low' 'High']
 ['Low' 'Low' 'Low' 'Low']
 ['High' 'Low' 'Low' 'Medium']]


Part 9: Target-Based Analysis
Use the following category-wise monthly sales targets:

sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])
Question 48: Target Comparison
Compare every store’s category sales against sales_targets.

Use NumPy broadcasting.

In [ ]:
import numpy as np

sales_data = np.array([
    [900000, 500000, 300000, 350000, 250000, 280000],
    [750000, 400000, 350000, 280000, 180000, 240000],
    [850000, 450000, 320000, 300000, 200000, 230000],
    [950000, 550000, 400000, 330000, 220000, 250000]
])

sales_targets = np.array([
    800000,
    450000,
    320000,
    300000,
    200000,
    230000
])

# Compare sales with targets using broadcasting
target_comparison = sales_data >= sales_targets

print(target_comparison)

[[ True  True False  True  True  True]
 [False False  True False False  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


Question 49: Target Achievement Matrix
Create a Boolean array where:

True means the store achieved the category target
False means the store failed to achieve the target

In [ ]:
import numpy as np

target_achievement = sales_data >= sales_targets

print(target_achievement)

[[ True  True False  True  True  True]
 [False False  True False False  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


Question 50: Target Achievement Count
Calculate the number of categories in which each store achieved its target.

In [ ]:
import numpy as np

target_achievement = sales_data >= sales_targets

target_count = np.sum(target_achievement, axis=1)

print(target_count)

[5 2 6 6]


Question 51: Best Target-Performing Store
Find the store that achieved the highest number of category targets.

In [ ]:
best_store = np.argmax(target_count)

print(stores[best_store])

Chennai


Question 52: Target Achievement by Category
Calculate how many stores achieved the target for each product category.

In [ ]:
category_target_count = np.sum(target_achievement, axis=0)

print(category_target_count)

[3 3 3 3 3 4]


Question 53: Sales Target Variance
Calculate the difference between actual sales and target sales for every store.

Use:

Variance = Actual Sales - Target Sales

In [ ]:
variance = sales_data - sales_targets

print(variance)

[[100000  50000 -20000  50000  50000  50000]
 [-50000 -50000  30000 -20000 -20000  10000]
 [ 50000      0      0      0      0      0]
 [150000 100000  80000  30000  20000  20000]]


Question 54: Percentage Above or Below Target
Calculate the percentage variance from the target using:

Percentage Variance =
(Actual Sales - Target Sales) / Target Sales × 100

In [ ]:
percentage_variance = ((sales_data - sales_targets) / sales_targets) * 100

percentage_variance = np.round(percentage_variance, 2)

print(percentage_variance)

[[ 12.5   11.11  -6.25  16.67  25.    21.74]
 [ -6.25 -11.11   9.38  -6.67 -10.     4.35]
 [  6.25   0.     0.     0.     0.     0.  ]
 [ 18.75  22.22  25.    10.    10.     8.7 ]]


Question 55: Stores Missing Electronics Target
Identify stores that failed to achieve the Electronics sales target.

In [ ]:
electronics_target = sales_targets[0]

missing_electronics = sales_data[:, 0] < electronics_target

print(stores[missing_electronics])

['Hyderabad']


Question 56: Stores Achieving All Targets
Check whether any store achieved its target in all six product categories.

Use np.all().

In [ ]:
all_targets = np.all(target_achievement, axis=1)

print(all_targets)

[False False  True  True]



Question 57: Stores Achieving At Least One Target
Identify stores that achieved at least one category target.

Use np.any().


In [ ]:
one_target = np.any(target_achievement, axis=1)

print(stores[one_target])

['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']


Part 10: Discount Scenario
SmartMart plans to offer category-wise discounts:

discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])
Question 58: Discount Amount Matrix
Calculate the discount amount for each store-category combination.

Use broadcasting.

In [ ]:
discount_rates = np.array([0.10, 0.05, 0.15, 0.12, 0.08, 0.10])

discount_amount = sales_data * discount_rates

print(discount_amount)

[[90000. 25000. 45000. 42000. 20000. 28000.]
 [75000. 20000. 52500. 33600. 14400. 24000.]
 [85000. 22500. 48000. 36000. 16000. 23000.]
 [95000. 27500. 60000. 39600. 17600. 25000.]]


Question 59: Sales After Discount
Calculate the net sales value after applying the category-wise discounts.

In [ ]:
discount_amount = sales_data * discount_rates

net_sales = sales_data - discount_amount

print(net_sales)

[[810000. 475000. 255000. 308000. 230000. 252000.]
 [675000. 380000. 297500. 246400. 165600. 216000.]
 [765000. 427500. 272000. 264000. 184000. 207000.]
 [855000. 522500. 340000. 290400. 202400. 225000.]]


Question 60: Profit After Discount
Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

In [10]:
Discounted Selling Price = Selling Price − Discount

=11000−1000=10000

So, the discounted selling price is 10,000.

1000=11000-1000-11000

11000−1000−11000=−1000

So:

−1000

=1000
	​


For profit after discount, the correct formula is:

New Profit=Discounted Selling Price−Cost Price


10000−9000=1000

So the profit is 1,000.

SyntaxError: invalid character '−' (U+2212) (4209672292.py, line 1)