Question 61: Profit Margin After Discount
Calculate the new profit margin after applying discounts.

In [ ]:
cost_price = 1400
selling_price = 1200
discount = 0.10

discounted_price = selling_price * (1 - discount)
profit_margin = ((discounted_price - cost_price) / discounted_price) * 100

print("New Profit Margin:", round(profit_margin, 2), "%")

New Profit Margin: -29.63 %


Question 62: Loss-Making Transactions
Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

In [ ]:
import numpy as np

categories = np.array([
    "Electronics", "Groceries", "Clothing",
    "Furniture", "Beauty", "Sports"
])

cost_price = 1400
selling_price = 1200

discounted_price = selling_price * (1 - discount_rates)

loss = discounted_price < cost_price

for category in categories[loss]:
    print(category)

Electronics
Groceries
Clothing
Furniture
Beauty
Sports


Question 63: Discount Impact
Calculate how much total revenue the company loses because of the proposed discounts.

In [ ]:
discounted_prices = selling_price * (1 - discount_rates)

revenue_loss = np.sum(selling_price - discounted_prices)

print("Total Revenue Loss:", revenue_loss)

Total Revenue Loss: 720.0


Question 64: Store Most Affected by Discounts
Identify the store that loses the highest amount of revenue due to discounts.

In [ ]:
import numpy as np

discount_rates = np.array([
    0.10,  # Electronics
    0.05,  # Groceries
    0.15,  # Clothing
    0.12,  # Furniture
    0.08,  # Beauty
    0.10   # Sports
])

selling_price = 1200

discount_amount = selling_price * discount_rates

max_index = np.argmax(discount_amount)

categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

print("Store most affected by discounts:", categories[max_index])
print("Revenue loss:", discount_amount[max_index])

Store most affected by discounts: Clothing
Revenue loss: 180.0


Part 11: Tax and Price Adjustment
The government introduces category-wise tax rates:

tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])
Question 65: Tax Collection Matrix
Calculate the tax collected on sales for each store and category.

In [ ]:
import numpy as np

tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

selling_price = 1200

tax_collected = selling_price * tax_rates

categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

for category, tax in zip(categories, tax_collected):
    print(category, ":", tax)

Electronics : 216.0
Groceries : 60.0
Clothing : 144.0
Furniture : 216.0
Beauty : 216.0
Sports : 144.0


Question 66: Sales Including Tax
Calculate the final customer billing value after adding tax.

In [ ]:
import numpy as np

tax_rates = np.array([
    0.18,  # Electronics
    0.05,  # Groceries
    0.12,  # Clothing
    0.18,  # Furniture
    0.18,  # Beauty
    0.12   # Sports
])

selling_price = 1200

final_price = selling_price * (1 + tax_rates)

categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

for category, price in zip(categories, final_price):
    print(category, ":", price)

Electronics : 1416.0
Groceries : 1260.0
Clothing : 1344.0000000000002
Furniture : 1416.0
Beauty : 1416.0
Sports : 1344.0000000000002


Question 67: Store-Wise Tax Collection
Calculate the total tax collected by each store.

In [ ]:
import numpy as np

tax_rates = np.array([0.18, 0.05, 0.12, 0.18, 0.18, 0.12])

selling_price = 1200

tax_collected = selling_price * tax_rates

# If each store has one category:
store_tax = tax_collected

for i, tax in enumerate(store_tax):
    print("Store", i + 1, ":", tax)

Store 1 : 216.0
Store 2 : 60.0
Store 3 : 144.0
Store 4 : 216.0
Store 5 : 216.0
Store 6 : 144.0


Question 68: Category-Wise Tax Collection
Calculate total tax collected for each category.



In [ ]:
import numpy as np

tax_rates = np.array([0.18, 0.05, 0.12, 0.18, 0.18, 0.12])
selling_price = 1200

categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

tax_collected = selling_price * tax_rates

for category, tax in zip(categories, tax_collected):
    print(category, ":", tax)

Electronics : 216.0
Groceries : 60.0
Clothing : 144.0
Furniture : 216.0
Beauty : 216.0
Sports : 144.0


Question 69: Highest Tax-Contributing Store
Identify the store that contributes the highest tax amount.

In [ ]:
import numpy as np

tax_rates = np.array([0.18, 0.05, 0.12, 0.18, 0.18, 0.12])
selling_price = 1200

tax_collected = selling_price * tax_rates

stores = np.array([
    "Store 1",
    "Store 2",
    "Store 3",
    "Store 4",
    "Store 5",
    "Store 6"
])

max_index = np.argmax(tax_collected)

print("Highest Tax-Contributing Store:", stores[max_index])
print("Tax Amount:", tax_collected[max_index])

Highest Tax-Contributing Store: Store 1
Tax Amount: 216.0


Part 12: Array Modification
Question 70: Updated Pune Electronics Sales
The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

In [ ]:
import numpy as np

# Original sales array
sales = np.array([
    [690000, 500000, 400000, 450000, 350000, 300000]
])

# Make a copy
updated_sales = sales.copy()

# Update Pune Electronics from 690000 to 740000
updated_sales[0, 0] = 740000

print("Updated Pune Electronics Sales:", updated_sales[0, 0])
print("Original Sales:", sales[0, 0])

Updated Pune Electronics Sales: 740000
Original Sales: 690000


Question 71: Revised Beauty Cost
Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

In [ ]:
import numpy as np

# Original cost array
cost = np.array([1400, 1400, 1400, 1400, 1400, 1400])

# Create a copy
updated_cost = cost.copy()

# Reduce Beauty cost by 8%
updated_cost = updated_cost * 0.92

print("Updated Cost Array:")
print(updated_cost)

Updated Cost Array:
[1288. 1288. 1288. 1288. 1288. 1288.]


Question 72: Furniture Cost Increase
Furniture costs increase by 12% for all stores.

Update only the Furniture column.

In [ ]:
import numpy as np

cost = np.array([
    [1400, 1400, 1400, 1400, 1400, 1400]
])
updated_cost = cost.copy()

updated_cost[:, 3] = updated_cost[:, 3] * 1.12

print("Original Cost Array:")
print(cost)

print("Updated Cost Array:")
print(updated_cost)

Original Cost Array:
[[1400 1400 1400 1400 1400 1400]]
Updated Cost Array:
[[1400 1400 1400 1568 1400 1400]]


Question 73: Store Closure Simulation
Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using np.delete().

In [ ]:
import numpy as np

sales = np.array([
    [690000, 500000, 400000, 450000, 350000, 300000],
    [600000, 450000, 380000, 420000, 330000, 280000]
])

cost = np.array([
    [500000, 400000, 300000, 350000, 280000, 250000],
    [450000, 350000, 280000, 320000, 250000, 220000]
])

sales_without_pune = np.delete(sales, 0, axis=0)
cost_without_pune = np.delete(cost, 0, axis=0)

print("Sales after removing Pune:")
print(sales_without_pune)

print("Cost after removing Pune:")
print(cost_without_pune)

Sales after removing Pune:
[[600000 450000 380000 420000 330000 280000]]
Cost after removing Pune:
[[450000 350000 280000 320000 250000 220000]]


Question 74: Adding a New Store
A new Delhi store is opened with the following data:

delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
Add Delhi to both arrays using np.vstack().

Also add "Delhi" to the stores array.

In [ ]:
import numpy as np

# Original sales and cost arrays
sales = np.array([
    [690000, 500000, 400000, 450000, 350000, 300000],
    [600000, 450000, 380000, 420000, 330000, 280000]
])

cost = np.array([
    [500000, 400000, 300000, 350000, 280000, 250000],
    [450000, 350000, 280000, 320000, 250000, 220000]
])

# Delhi data
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

# Add Delhi using vstack()
sales = np.vstack((sales, delhi_sales))
cost = np.vstack((cost, delhi_cost))

# Add Delhi to stores array
stores = np.array(["Pune", "Mumbai"])
stores = np.append(stores, "Delhi")

print("Updated Stores:")
print(stores)

print("\nUpdated Sales:")
print(sales)

print("\nUpdated Cost:")
print(cost)

Updated Stores:
['Pune' 'Mumbai' 'Delhi']

Updated Sales:
[[690000 500000 400000 450000 350000 300000]
 [600000 450000 380000 420000 330000 280000]
 [880000 475000 330000 290000 215000 250000]]

Updated Cost:
[[500000 400000 300000 350000 280000 250000]
 [450000 350000 280000 320000 250000 220000]
 [665000 360000 235000 215000 145000 180000]]


Question 75: Adding a New Product Category
SmartMart starts selling Home Appliances.

home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
Add the new category as a column using np.column_stack() or np.hstack().

In [ ]:
import numpy as np

# Existing sales array
sales = np.array([
    [690000, 500000, 400000, 450000, 350000],
    [600000, 450000, 380000, 420000, 330000],
    [880000, 475000, 330000, 290000, 215000],
    [700000, 425000, 360000, 410000, 300000],
    [650000, 400000, 350000, 390000, 280000]
])

# Existing cost array
cost = np.array([
    [500000, 400000, 300000, 350000, 280000],
    [450000, 350000, 280000, 320000, 250000],
    [665000, 360000, 235000, 215000, 145000],
    [520000, 330000, 270000, 310000, 240000],
    [480000, 310000, 260000, 290000, 220000]
])

# New Home Appliances data
home_appliance_sales = np.array([
    360000, 325000, 390000, 420000, 295000
])

home_appliance_cost = np.array([
    265000, 240000, 285000, 305000, 225000
])

# Add Home Appliances as a new column
sales = np.column_stack((sales, home_appliance_sales))
cost = np.column_stack((cost, home_appliance_cost))

print("Updated Sales:")
print(sales)

print("\nUpdated Cost:")
print(cost)

Updated Sales:
[[690000 500000 400000 450000 350000 360000]
 [600000 450000 380000 420000 330000 325000]
 [880000 475000 330000 290000 215000 390000]
 [700000 425000 360000 410000 300000 420000]
 [650000 400000 350000 390000 280000 295000]]

Updated Cost:
[[500000 400000 300000 350000 280000 265000]
 [450000 350000 280000 320000 250000 240000]
 [665000 360000 235000 215000 145000 285000]
 [520000 330000 270000 310000 240000 305000]
 [480000 310000 260000 290000 220000 225000]]


Part 13: Sorting and Ranking
Question 76: Sort Stores by Sales
Sort stores in ascending order based on total sales.

Display store names and sales totals.



In [ ]:
import numpy as np

stores = np.array(["Pune", "Mumbai", "Delhi", "Bangalore", "Chennai"])

sales = np.array([
    [690000, 500000, 400000, 450000, 350000, 300000],
    [600000, 450000, 380000, 420000, 330000, 280000],
    [880000, 475000, 330000, 290000, 215000, 250000],
    [700000, 425000, 360000, 410000, 300000, 320000],
    [650000, 400000, 350000, 390000, 280000, 295000]
])

sales_totals = np.sum(sales, axis=1)
order = np.argsort(sales_totals)

for i in order:
    print(stores[i], ":", sales_totals[i])

Chennai : 2365000
Delhi : 2440000
Mumbai : 2460000
Bangalore : 2515000
Pune : 2690000


Question 77: Rank Stores by Profit
Rank stores from highest to lowest total profit.

Use np.argsort().

In [ ]:
import numpy as np

stores = np.array(["Pune", "Mumbai", "Delhi", "Bangalore", "Chennai"])

sales = np.array([
    [690000, 500000, 400000, 450000, 350000, 300000],
    [600000, 450000, 380000, 420000, 330000, 280000],
    [880000, 475000, 330000, 290000, 215000, 250000],
    [700000, 425000, 360000, 410000, 300000, 320000],
    [650000, 400000, 350000, 390000, 280000, 295000]
])

cost = np.array([
    [500000, 400000, 300000, 350000, 280000, 250000],
    [450000, 350000, 280000, 320000, 250000, 220000],
    [665000, 360000, 235000, 215000, 145000, 180000],
    [520000, 330000, 270000, 310000, 240000, 260000],
    [480000, 310000, 260000, 290000, 220000, 225000]
])

# Calculate total profit
sales_totals = np.sum(sales, axis=1)
cost_totals = np.sum(cost, axis=1)
profit = sales_totals - cost_totals

# Rank from highest to lowest using np.argsort()
order = np.argsort(profit)[::-1]

print("Stores ranked by total profit:")

for i in order:
    print(stores[i], ":", profit[i])

Stores ranked by total profit:
Delhi : 640000
Pune : 610000
Mumbai : 590000
Bangalore : 585000
Chennai : 580000



Question 78: Sort Categories by Revenue
Sort product categories from highest to lowest total revenue.



In [ ]:
import numpy as np

categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports",
    "Home Appliances"
])

# Total revenue for each category
category_revenue = np.sum(sales, axis=0)

# Sort highest to lowest
order = np.argsort(category_revenue)[::-1]

print("Categories sorted by revenue:")

for i in order:
    print(categories[i], ":", category_revenue[i])

Categories sorted by revenue:
Electronics : 3520000
Groceries : 2250000
Furniture : 1960000
Clothing : 1820000
Beauty : 1475000
Sports : 1445000


Question 79: Top Three Store-Category Sales
Find the three highest individual sales values in the complete sales matrix.

Display their:

Sales value
Store name
Category name

In [ ]:
import numpy as np

stores = np.array(["Pune", "Mumbai", "Delhi", "Bangalore", "Chennai"])

categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

sales = np.array([
    [690000, 500000, 400000, 450000, 350000, 300000],
    [600000, 450000, 380000, 420000, 330000, 280000],
    [880000, 475000, 330000, 290000, 215000, 250000],
    [700000, 425000, 360000, 410000, 300000, 320000],
    [650000, 400000, 350000, 390000, 280000, 295000]
])

# Get indices of the 3 highest sales
flat_indices = np.argsort(sales.ravel())[-3:][::-1]

print("Top 3 Store-Category Sales:")

for index in flat_indices:
    store_index, category_index = np.unravel_index(index, sales.shape)
    print(
        "Sales:", sales[store_index, category_index],
        "| Store:", stores[store_index],
        "| Category:", categories[category_index]
    )

Top 3 Store-Category Sales:
Sales: 880000 | Store: Delhi | Category: Electronics
Sales: 700000 | Store: Bangalore | Category: Electronics
Sales: 690000 | Store: Pune | Category: Electronics



Question 80: Bottom Three Profits
Find the three lowest profit values in the profit matrix.

In [ ]:
import numpy as np
profit = sales - cost
bottom_3 = np.argsort(profit.ravel())[:3]

print("Bottom 3 Profit Values:")

for index in bottom_3:
    store_index, category_index = np.unravel_index(index, profit.shape)
    print(
        "Profit:", profit[store_index, category_index],
        "| Store:", stores[store_index],
        "| Category:", categories[category_index]
    )

Bottom 3 Profit Values:
Profit: 50000 | Store: Pune | Category: Sports
Profit: 60000 | Store: Mumbai | Category: Sports
Profit: 60000 | Store: Bangalore | Category: Sports


Part 14: Statistical Analysis
Question 81: Sales Statistics
Calculate the following for the complete sales array:

Minimum
Maximum
Mean
Median
Standard deviation
Variance
25th percentile
50th percentile
75th percentile

In [ ]:
import numpy as np

# Complete sales array
sales = np.array([
    [690000, 500000, 400000, 450000, 350000, 300000],
    [600000, 450000, 380000, 420000, 330000, 280000],
    [880000, 475000, 330000, 290000, 215000, 250000],
    [700000, 425000, 360000, 410000, 300000, 320000],
    [650000, 400000, 350000, 390000, 280000, 295000]
])

print("Minimum:", np.min(sales))
print("Maximum:", np.max(sales))
print("Mean:", np.mean(sales))
print("Median:", np.median(sales))
print("Standard Deviation:", np.std(sales))
print("Variance:", np.var(sales))
print("25th Percentile:", np.percentile(sales, 25))
print("50th Percentile:", np.percentile(sales, 50))
print("75th Percentile:", np.percentile(sales, 75))

Minimum: 215000
Maximum: 880000
Mean: 415666.6666666667
Median: 385000.0
Standard Deviation: 149815.07118963552
Variance: 22444555555.555557
25th Percentile: 305000.0
50th Percentile: 385000.0
75th Percentile: 450000.0


Question 82: Store-Wise Standard Deviation
Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

In [ ]:
import numpy as np

stores = np.array(["Pune", "Mumbai", "Delhi", "Bangalore", "Chennai"])

sales = np.array([
    [690000, 500000, 400000, 450000, 350000, 300000],
    [600000, 450000, 380000, 420000, 330000, 280000],
    [880000, 475000, 330000, 290000, 215000, 250000],
    [700000, 425000, 360000, 410000, 300000, 320000],
    [650000, 400000, 350000, 390000, 280000, 295000]
])

# Standard deviation for each store
store_std = np.std(sales, axis=1)

for store, std in zip(stores, store_std):
    print(store, ":", std)

# Store with the most variation
max_index = np.argmax(store_std)

print("\nStore with most variation:", stores[max_index])
print("Highest Standard Deviation:", store_std[max_index])

Pune : 125885.75067187796
Mumbai : 101653.0045465127
Delhi : 227113.53010235992
Bangalore : 133242.15632532453
Chennai : 122692.59236898625

Store with most variation: Delhi
Highest Standard Deviation: 227113.53010235992


Question 83: Category-Wise Standard Deviation
Determine which product category has the highest variation in sales across stores.

In [ ]:
import numpy as np

categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

sales = np.array([
    [690000, 500000, 400000, 450000, 350000, 300000],
    [600000, 450000, 380000, 420000, 330000, 280000],
    [880000, 475000, 330000, 290000, 215000, 250000],
    [700000, 425000, 360000, 410000, 300000, 320000],
    [650000, 400000, 350000, 390000, 280000, 295000]
])

# Standard deviation for each category
category_std = np.std(sales, axis=0)

for category, std in zip(categories, category_std):
    print(category, ":", std)

# Category with highest variation
max_index = np.argmax(category_std)

print("\nCategory with highest variation:", categories[max_index])
print("Highest Standard Deviation:", category_std[max_index])

Electronics : 94783.96488858228
Groceries : 35355.33905932738
Clothing : 24166.091947189143
Furniture : 54552.72678794342
Beauty : 46690.470119715006
Sports : 23323.807579381202

Category with highest variation: Electronics
Highest Standard Deviation: 94783.96488858228


Question 84: Sales Above Company Average
Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.

In [ ]:
import numpy as np

sales = np.array([
    [690000, 500000, 400000, 450000, 350000, 300000],
    [600000, 450000, 380000, 420000, 330000, 280000],
    [880000, 475000, 330000, 290000, 215000, 250000],
    [700000, 425000, 360000, 410000, 300000, 320000],
    [650000, 400000, 350000, 390000, 280000, 295000]
])

# Company-wide average sales
average_sales = np.mean(sales)

# Count sales above the average
above_average = np.sum(sales > average_sales)

print("Company-wide Average Sales:", average_sales)
print("Number of Sales Above Average:", above_average)

Company-wide Average Sales: 415666.6666666667
Number of Sales Above Average: 11


Question 85: Outlier Detection
Treat any sales value greater than:

Mean + 1.5 × Standard Deviation
as a high-value outlier.

Identify all such sales values.

In [ ]:
import numpy as np

sales = np.array([
    [690000, 500000, 400000, 450000, 350000, 300000],
    [600000, 450000, 380000, 420000, 330000, 280000],
    [880000, 475000, 330000, 290000, 215000, 250000],
    [700000, 425000, 360000, 410000, 300000, 320000],
    [650000, 400000, 350000, 390000, 280000, 295000]
])

# Calculate mean and standard deviation
mean = np.mean(sales)
std = np.std(sales)

# Outlier threshold
threshold = mean + 1.5 * std

# Find high-value outliers
outliers = sales[sales > threshold]

print("Mean:", mean)
print("Standard Deviation:", std)
print("Outlier Threshold:", threshold)
print("High-Value Outliers:", outliers)

Mean: 415666.6666666667
Standard Deviation: 149815.07118963552
Outlier Threshold: 640389.2734511199
High-Value Outliers: [690000 880000 700000 650000]


Part 15: Reshaping and Transformation
Question 86: Flatten Sales Data
Convert the two-dimensional sales array into a one-dimensional array using:

flatten()
ravel()
Explain the difference between the two methods.

In [ ]:
import numpy as np

sales = np.array([
    [690000, 500000, 400000, 450000, 350000, 300000],
    [600000, 450000, 380000, 420000, 330000, 280000],
    [880000, 475000, 330000, 290000, 215000, 250000],
    [700000, 425000, 360000, 410000, 300000, 320000],
    [650000, 400000, 350000, 390000, 280000, 295000]
])

# Using flatten()
sales_flatten = sales.flatten()

# Using ravel()
sales_ravel = sales.ravel()

print("Using flatten():")
print(sales_flatten)

print("\nUsing ravel():")
print(sales_ravel)

print("\nDifference:")
print("flatten() creates a copy of the array.")
print("ravel() usually returns a view of the original array.")

Using flatten():
[690000 500000 400000 450000 350000 300000 600000 450000 380000 420000
 330000 280000 880000 475000 330000 290000 215000 250000 700000 425000
 360000 410000 300000 320000 650000 400000 350000 390000 280000 295000]

Using ravel():
[690000 500000 400000 450000 350000 300000 600000 450000 380000 420000
 330000 280000 880000 475000 330000 290000 215000 250000 700000 425000
 360000 410000 300000 320000 650000 400000 350000 390000 280000 295000]

Difference:
flatten() creates a copy of the array.
ravel() usually returns a view of the original array.


Question 87: Reshape Sales Data
Reshape the 5 × 6 sales array into:

3 × 10
10 × 3
2 × 15
15 × 2
Verify that no data is lost.

In [ ]:
import numpy as np

sales = np.array([
    [690000, 500000, 400000, 450000, 350000, 300000],
    [600000, 450000, 380000, 420000, 330000, 280000],
    [880000, 475000, 330000, 290000, 215000, 250000],
    [700000, 425000, 360000, 410000, 300000, 320000],
    [650000, 400000, 350000, 390000, 280000, 295000]
])

# Reshape into different dimensions
sales_3x10 = sales.reshape(3, 10)
sales_10x3 = sales.reshape(10, 3)
sales_2x15 = sales.reshape(2, 15)
sales_15x2 = sales.reshape(15, 2)

print("3 × 10:")
print(sales_3x10)

print("\n10 × 3:")
print(sales_10x3)

print("\n2 × 15:")
print(sales_2x15)

print("\n15 × 2:")
print(sales_15x2)

# Verify no data is lost
print("\nOriginal total:", np.sum(sales))
print("3 × 10 total:", np.sum(sales_3x10))
print("10 × 3 total:", np.sum(sales_10x3))
print("2 × 15 total:", np.sum(sales_2x15))
print("15 × 2 total:", np.sum(sales_15x2))

print("\nData lost:", np.sum(sales) != np.sum(sales_3x10))

3 × 10:
[[690000 500000 400000 450000 350000 300000 600000 450000 380000 420000]
 [330000 280000 880000 475000 330000 290000 215000 250000 700000 425000]
 [360000 410000 300000 320000 650000 400000 350000 390000 280000 295000]]

10 × 3:
[[690000 500000 400000]
 [450000 350000 300000]
 [600000 450000 380000]
 [420000 330000 280000]
 [880000 475000 330000]
 [290000 215000 250000]
 [700000 425000 360000]
 [410000 300000 320000]
 [650000 400000 350000]
 [390000 280000 295000]]

2 × 15:
[[690000 500000 400000 450000 350000 300000 600000 450000 380000 420000
  330000 280000 880000 475000 330000]
 [290000 215000 250000 700000 425000 360000 410000 300000 320000 650000
  400000 350000 390000 280000 295000]]

15 × 2:
[[690000 500000]
 [400000 450000]
 [350000 300000]
 [600000 450000]
 [380000 420000]
 [330000 280000]
 [880000 475000]
 [330000 290000]
 [215000 250000]
 [700000 425000]
 [360000 410000]
 [300000 320000]
 [650000 400000]
 [350000 390000]
 [280000 295000]]

Original total: 12470000
3

Question 88: Transpose Sales Data
Transpose the sales array so that:

Rows represent product categories
Columns represent stores
Display the new shape.

In [ ]:
import numpy as np

sales = np.array([
    [690000, 500000, 400000, 450000, 350000, 300000],
    [600000, 450000, 380000, 420000, 330000, 280000],
    [880000, 475000, 330000, 290000, 215000, 250000],
    [700000, 425000, 360000, 410000, 300000, 320000],
    [650000, 400000, 350000, 390000, 280000, 295000]
])

# Transpose sales array
sales_transposed = sales.T

print("Transposed Sales Array:")
print(sales_transposed)

print("\nNew Shape:", sales_transposed.shape)

Transposed Sales Array:
[[690000 600000 880000 700000 650000]
 [500000 450000 475000 425000 400000]
 [400000 380000 330000 360000 350000]
 [450000 420000 290000 410000 390000]
 [350000 330000 215000 300000 280000]
 [300000 280000 250000 320000 295000]]

New Shape: (6, 5)


Question 89: Combined Sales and Cost Array
Stack sales_data and cost_data vertically.

Display the resulting shape.

In [ ]:
import numpy as np

sales_data = np.array([
    [690000, 500000, 400000, 450000, 350000, 300000],
    [600000, 450000, 380000, 420000, 330000, 280000],
    [880000, 475000, 330000, 290000, 215000, 250000],
    [700000, 425000, 360000, 410000, 300000, 320000],
    [650000, 400000, 350000, 390000, 280000, 295000]
])

cost_data = np.array([
    [500000, 400000, 300000, 350000, 280000, 250000],
    [450000, 350000, 280000, 320000, 250000, 220000],
    [665000, 360000, 235000, 215000, 145000, 180000],
    [520000, 330000, 270000, 310000, 240000, 260000],
    [480000, 310000, 260000, 290000, 220000, 225000]
])

# Stack sales and cost vertically
combined_array = np.vstack((sales_data, cost_data))

print("Combined Sales and Cost Array:")
print(combined_array)

print("\nResulting Shape:", combined_array.shape)

Combined Sales and Cost Array:
[[690000 500000 400000 450000 350000 300000]
 [600000 450000 380000 420000 330000 280000]
 [880000 475000 330000 290000 215000 250000]
 [700000 425000 360000 410000 300000 320000]
 [650000 400000 350000 390000 280000 295000]
 [500000 400000 300000 350000 280000 250000]
 [450000 350000 280000 320000 250000 220000]
 [665000 360000 235000 215000 145000 180000]
 [520000 330000 270000 310000 240000 260000]
 [480000 310000 260000 290000 220000 225000]]

Resulting Shape: (10, 6)


Question 90: Store-Level Combined Data
Create a three-dimensional array where:

First layer contains sales data
Second layer contains cost data
Use np.stack().

Display the shape of the new array.

Part 16: Missing Data Scenario
The company discovers that some sales values were not recorded.

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

In [ ]:
import numpy as np

sales_data = np.array([
    [690000, 500000, 400000, 450000, 350000, 300000],
    [600000, 450000, 380000, 420000, 330000, 280000],
    [880000, 475000, 330000, 290000, 215000, 250000],
    [700000, 425000, 360000, 410000, 300000, 320000],
    [650000, 400000, 350000, 390000, 280000, 295000]
])

cost_data = np.array([
    [500000, 400000, 300000, 350000, 280000, 250000],
    [450000, 350000, 280000, 320000, 250000, 220000],
    [665000, 360000, 235000, 215000, 145000, 180000],
    [520000, 330000, 270000, 310000, 240000, 260000],
    [480000, 310000, 260000, 290000, 220000, 225000]
])

combined_data = np.stack((sales_data, cost_data))

print("3D Combined Array:")
print(combined_data)

print("\nShape of the new array:", combined_data.shape)

3D Combined Array:
[[[690000 500000 400000 450000 350000 300000]
  [600000 450000 380000 420000 330000 280000]
  [880000 475000 330000 290000 215000 250000]
  [700000 425000 360000 410000 300000 320000]
  [650000 400000 350000 390000 280000 295000]]

 [[500000 400000 300000 350000 280000 250000]
  [450000 350000 280000 320000 250000 220000]
  [665000 360000 235000 215000 145000 180000]
  [520000 330000 270000 310000 240000 260000]
  [480000 310000 260000 290000 220000 225000]]]

Shape of the new array: (2, 5, 6)


Part 16: Missing Data Scenario
The company discovers that some sales values were not recorded.

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
Question 91: Missing Value Detection
Find:

Total number of missing values
Location of missing values
Stores and categories containing missing values

In [1]:
import numpy as np

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

missing_mask = np.isnan(sales_with_missing)

print("Total number of missing values:", missing_mask.sum())

locations = np.argwhere(missing_mask)
print("Locations of missing values:", locations)

stores = np.unique(locations[:, 0]) + 1
categories = np.unique(locations[:, 1]) + 1

print("Stores containing missing values:", stores)
print("Categories containing missing values:", categories)

Total number of missing values: 4
Locations of missing values: [[0 2]
 [1 3]
 [3 1]
 [4 4]]
Stores containing missing values: [1 2 4 5]
Categories containing missing values: [2 3 4 5]


Question 92: Replace Missing Values with Zero
Replace all missing sales values with zero.

In [2]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

sales_with_missing = np.nan_to_num(sales_with_missing, nan=0)

print(sales_with_missing)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


Question 93: Replace with Company Average
Replace missing values with the overall average of available sales values.

Use np.nanmean().

In [3]:
import numpy as np

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

# Calculate overall average, ignoring NaN
company_average = np.nanmean(sales_with_missing)

print("Company Average:", company_average)

# Replace NaN values with the company average
sales_filled = np.where(
    np.isnan(sales_with_missing),
    company_average,
    sales_with_missing
)

print(sales_filled)

Company Average: 398846.1538461539
[[ 850000.          420000.          398846.15384615  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          398846.15384615
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          398846.15384615  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   398846.15384615  205000.        ]]


Question 94: Replace with Category Average
Replace each missing value with the average sales value of its respective product category.

In [4]:
import numpy as np

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

# Calculate average for each category (column)
category_averages = np.nanmean(sales_with_missing, axis=0)

print("Category averages:", category_averages)

# Find missing values
missing = np.isnan(sales_with_missing)

# Replace missing values with their category average
sales_filled = sales_with_missing.copy()
sales_filled[missing] = np.take(category_averages, np.where(missing)[1])

print(sales_filled)

Category averages: [858000. 418750. 322500. 276250. 208750. 235000.]
[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


Question 95: Missing Value Impact
Compare total sales before and after replacing missing values with zero.

In [5]:
import numpy as np

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

# Total before replacement (ignoring NaN)
total_before = np.nansum(sales_with_missing)

# Replace missing values with zero
sales_zero = np.nan_to_num(sales_with_missing, nan=0)

# Total after replacement
total_after = np.sum(sales_zero)

print("Total sales before:", total_before)
print("Total sales after:", total_after)
print("Difference:", total_after - total_before)

Total sales before: 10370000.0
Total sales after: 10370000.0
Difference: 0.0


Part 17: Conditional Business Decisions
Question 96: Store Performance Labels
Classify each store based on total sales:

"Excellent": Total sales above ₹28,00,000
"Good": Total sales between ₹24,00,000 and ₹28,00,000
"Needs Improvement": Total sales below ₹24,00,000
Use np.select().

In [ ]:
import numpy as np

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

# Calculate total sales for each store, ignoring missing values
store_totals = np.nansum(sales_with_missing, axis=1)

conditions = [
    store_totals > 2800000,
    (store_totals >= 2400000) & (store_totals <= 2800000),
    store_totals < 2400000
]

# Assign labels
labels = [
    "Excellent",
    "Good",
    "Needs Improvement"
]

performance = np.select(conditions, labels)

print("Store totals:", store_totals)
print("Performance:", performance)

Question 97: Profitability Classification
Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000
"Profitable": Profit between ₹1,00,000 and ₹2,00,000
"Low Profit": Profit below ₹1,00,000
"Loss": Profit below zero

In [10]:
import numpy as np

conditions = [
    sales_with_missing < 0,
    sales_with_missing < 100000,
    sales_with_missing <= 200000,
    sales_with_missing > 200000
]

labels = [
    "Loss",
    "Low Profit",
    "Profitable",
    "Highly Profitable"
]

classification = np.select(conditions, labels, default="Missing")

print(classification)

[['Highly Profitable' 'Highly Profitable' 'Missing' 'Highly Profitable'
  'Profitable' 'Highly Profitable']
 ['Highly Profitable' 'Highly Profitable' 'Highly Profitable' 'Missing'
  'Highly Profitable' 'Highly Profitable']
 ['Highly Profitable' 'Highly Profitable' 'Highly Profitable'
  'Highly Profitable' 'Profitable' 'Highly Profitable']
 ['Highly Profitable' 'Missing' 'Highly Profitable' 'Highly Profitable'
  'Highly Profitable' 'Highly Profitable']
 ['Highly Profitable' 'Highly Profitable' 'Highly Profitable'
  'Highly Profitable' 'Missing' 'Highly Profitable']]


Question 98: Expansion Recommendation
A store is eligible for expansion when:

Total sales are above ₹25,00,000
Total profit is above ₹7,00,000
Overall profit margin is above 25%
Identify eligible stores.

In [14]:
import numpy as np

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

profit = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

total_sales = np.nansum(sales_with_missing, axis=1)
total_profit = np.sum(profit, axis=1)

profit_margin = (total_profit / total_sales) * 100

eligible = (
    (total_sales > 2500000) &
    (total_profit > 700000) &
    (profit_margin > 25)
)

print("Eligible Stores:", np.where(eligible)[0] + 1)

Eligible Stores: []


Question 99: Category Promotion Recommendation
A product category should receive additional promotion when:

Average sales are below ₹3,00,000
Profit margin is above 25%
Identify the categories that satisfy these conditions.

In [15]:
import numpy as np

# Average sales for each category
avg_sales = np.nanmean(sales_with_missing, axis=0)

# Total sales and profit for each category
category_sales = np.nansum(sales_with_missing, axis=0)
category_profit = np.sum(profit, axis=0)

# Profit margin for each category
profit_margin = (category_profit / category_sales) * 100

# Promotion conditions
promotion = (
    (avg_sales < 300000) &
    (profit_margin > 25)
)

print("Categories for additional promotion:",
      np.where(promotion)[0] + 1)

Categories for additional promotion: [4 5 6]


Question 100: Cost Optimization Recommendation
Find store-category combinations where:

Cost is greater than ₹2,50,000
Profit margin is below 25%
These combinations should be reviewed for cost optimization.

In [19]:
import numpy as np

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

profit = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

profit_margin = (profit / sales_with_missing) * 100

conditions = (cost_data > 250000) & (profit_margin < 25)

locations = np.argwhere(conditions)

print("Store-Category combinations:")
print(locations)

Store-Category combinations:
[]


Part 18: Inventory Scenario
Use the following inventory arrays:

opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])
Question 101: Closing Stock
Calculate closing stock using:

Closing Stock = Opening Stock - Units Sold

In [21]:
import numpy as np

opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

closing_stock = opening_stock - units_sold

print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


Question 101: Closing Stock
Calculate closing stock using:

Closing Stock = Opening Stock - Units Sold

In [3]:
import numpy as np

opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

closing_stock = opening_stock - units_sold

print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


Question 102: Low-Stock Identification
Identify store-category combinations where closing stock is below 30 units.

In [4]:
import numpy as np

closing_stock = opening_stock - units_sold

low_stock = closing_stock < 30

locations = np.argwhere(low_stock)

print("Low-stock store-category combinations:")

for store, category in locations:
    print(f"Store {store + 1}, Category {category + 1}")

Low-stock store-category combinations:
Store 1, Category 1
Store 1, Category 4
Store 2, Category 1
Store 2, Category 4
Store 3, Category 1
Store 3, Category 4
Store 4, Category 1
Store 5, Category 1
Store 5, Category 4


Question 103: Stock Availability Percentage
Calculate the percentage of opening stock that remains unsold.

In [5]:
import numpy as np

closing_stock = opening_stock - units_sold

stock_availability = (closing_stock / opening_stock) * 100

print(stock_availability)

[[20.83333333 15.55555556 20.         27.77777778 24.         22.22222222]
 [22.72727273 16.         17.85714286 25.         22.22222222 22.5       ]
 [19.23076923 16.66666667 15.625      29.41176471 25.         23.52941176]
 [16.66666667 14.54545455 15.71428571 25.         21.66666667 20.45454545]
 [25.         17.5        21.15384615 26.66666667 25.         25.        ]]


Question 104: Fast-Moving Products
A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

In [6]:
import numpy as np

closing_stock = opening_stock - units_sold

sold_percentage = (units_sold / opening_stock) * 100

fast_moving = sold_percentage > 80

locations = np.argwhere(fast_moving)

print("Fast-moving store-category combinations:")

for store, category in locations:
    print(f"Store {store + 1}, Category {category + 1}")

Fast-moving store-category combinations:
Store 1, Category 2
Store 2, Category 2
Store 2, Category 3
Store 3, Category 1
Store 3, Category 2
Store 3, Category 3
Store 4, Category 1
Store 4, Category 2
Store 4, Category 3
Store 5, Category 2


Question 105: Category-Wise Units Sold
Calculate the total units sold for each product category.

In [7]:
import numpy as np

category_units_sold = np.sum(units_sold, axis=0)

print(category_units_sold)

[ 485 1950 1240  345  980  720]


Question 106: Store-Wise Units Sold
Calculate total units sold by each store.

In [8]:
import numpy as np

store_units_sold = np.sum(units_sold, axis=1)

print(store_units_sold)

[1110 1175 1095 1390  950]


Question 107: Best Store by Unit Sales
Identify the store that sold the highest total number of units.

In [9]:
import numpy as np

store_units_sold = np.sum(units_sold, axis=1)

best_store = np.argmax(store_units_sold) + 1

print("Best Store:", best_store)
print("Units Sold:", store_units_sold[best_store - 1])

Best Store: 4
Units Sold: 1390


Question 108: Reorder Requirement
A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.

In [10]:
import numpy as np

closing_stock = opening_stock - units_sold

reorder = closing_stock < 25

print(reorder)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


Question 109: Reorder Quantity
Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

In [11]:
import numpy as np

closing_stock = opening_stock - units_sold

reorder_quantity = np.where(
    closing_stock < 25,
    100 - closing_stock,
    0
)

print(reorder_quantity)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


Part 19: Advanced NumPy Questions
Question 110: Cumulative Store Sales
Calculate cumulative category sales for each store using np.cumsum().

In [14]:
import numpy as np

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

cumulative_sales = np.nancumsum(sales_with_missing, axis=1)

print(cumulative_sales)

[[ 850000. 1270000. 1270000. 1545000. 1735000. 1960000.]
 [ 780000. 1240000. 1535000. 1535000. 1745000. 1985000.]
 [ 920000. 1310000. 1650000. 1910000. 2095000. 2310000.]
 [1050000. 1050000. 1425000. 1770000. 2020000. 2310000.]
 [ 690000. 1095000. 1375000. 1600000. 1600000. 1805000.]]


Question 111: Cumulative Company Sales
Flatten the sales array and calculate cumulative company sales.

In [15]:
import numpy as np

sales_flat = sales_with_missing.flatten()

cumulative_company_sales = np.nancumsum(sales_flat)

print(cumulative_company_sales)

[  850000.  1270000.  1270000.  1545000.  1735000.  1960000.  2740000.
  3200000.  3495000.  3495000.  3705000.  3945000.  4865000.  5255000.
  5595000.  5855000.  6040000.  6255000.  7305000.  7305000.  7680000.
  8025000.  8275000.  8565000.  9255000.  9660000.  9940000. 10165000.
 10165000. 10370000.]


Question 112: Sales Difference Between Categories
Calculate the difference between consecutive category sales for each store using np.diff().

In [16]:
import numpy as np

sales_difference = np.diff(sales_with_missing, axis=1)

print(sales_difference)

[[-430000.      nan      nan  -85000.   35000.]
 [-320000. -165000.      nan      nan   30000.]
 [-530000.  -50000.  -80000.  -75000.   30000.]
 [     nan      nan  -30000.  -95000.   40000.]
 [-285000. -125000.  -55000.      nan      nan]]


Question 113: Unique Sales Values
Find all unique sales values in sales_data.

Also count the frequency of each value.

In [17]:
import numpy as np

sales_data = sales_with_missing[~np.isnan(sales_with_missing)]

unique_values, counts = np.unique(sales_data, return_counts=True)

print("Unique Sales Values:")
print(unique_values)

print("Frequency of Each Value:")
print(counts)

Unique Sales Values:
[ 185000.  190000.  205000.  210000.  215000.  225000.  240000.  250000.
  260000.  275000.  280000.  290000.  295000.  340000.  345000.  375000.
  390000.  405000.  420000.  460000.  690000.  780000.  850000.  920000.
 1050000.]
Frequency of Each Value:
[1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


Question 114: Search for Specific Sales
Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [18]:
import numpy as np

locations = np.argwhere(sales_with_missing == 420000)

print("Location of ₹4,20,000:")
print(locations)

Location of ₹4,20,000:
[[0 1]]


Question 115: Compare Sales and Cost
Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using np.all().

In [20]:
import numpy as np

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

sales_vs_cost = sales_with_missing > cost_data

print("Sales greater than Cost:")
print(sales_vs_cost)

all_profitable = np.all(sales_vs_cost)

print("Are all combinations profitable?", all_profitable)



Sales greater than Cost:
[[ True  True False  True  True  True]
 [ True  True  True False  True  True]
 [ True  True  True  True  True  True]
 [ True False  True  True  True  True]
 [ True  True  True  True False  True]]
Are all combinations profitable? False


Question 116: Clip Profit Values
For reporting purposes, management wants profit values limited to:

Minimum: ₹75,000
Maximum: ₹2,50,000
Use np.clip() to create a reporting profit array.

In [22]:
import numpy as np

profit = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

reporting_profit = np.clip(profit, 75000, 250000)

print(reporting_profit)

[[250000 250000 220000 205000 125000 160000]
 [250000 250000 210000 225000 140000 170000]
 [250000 250000 245000 195000 120000 155000]
 [250000 250000 250000 250000 165000 205000]
 [250000 250000 205000 170000 115000 145000]]



Question 117: Normalize Sales Data
Normalize all sales values using min-max normalization:

Normalized Sales =
(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)


In [23]:
import numpy as np

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

minimum = np.nanmin(sales_with_missing)
maximum = np.nanmax(sales_with_missing)

normalized_sales = (sales_with_missing - minimum) / (maximum - minimum)

print(normalized_sales)

[[0.76878613 0.2716763         nan 0.10404624 0.00578035 0.04624277]
 [0.68786127 0.31791908 0.12716763        nan 0.02890173 0.06358382]
 [0.84971098 0.23699422 0.17919075 0.0867052  0.         0.03468208]
 [1.                nan 0.21965318 0.1849711  0.07514451 0.12138728]
 [0.58381503 0.25433526 0.10982659 0.04624277        nan 0.02312139]]


Question 118: Standardize Sales Data
Standardize sales using:

Standardized Sales =
(Sales - Mean Sales) / Standard Deviation

In [24]:
import numpy as np

mean_sales = np.nanmean(sales_with_missing)
std_sales = np.nanstd(sales_with_missing)

standardized_sales = (sales_with_missing - mean_sales) / std_sales

print(standardized_sales)

[[ 1.86835558  0.08760406         nan -0.51288192 -0.86489095 -0.71994606]
 [ 1.5784658   0.25325536 -0.43005627         nan -0.78206529 -0.65782682]
 [ 2.15824537 -0.03663442 -0.24369855 -0.57500116 -0.88559736 -0.76135888]
 [ 2.69661211         nan -0.09875366 -0.22299214 -0.61641399 -0.45076269]
 [ 1.20575036  0.02548482 -0.49217551 -0.71994606         nan -0.80277171]]



Question 119: Round Values
Convert profit margin values into:

Two decimal places
Nearest whole number
Floor values
Ceiling values

In [26]:
import numpy as np

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

profit = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

total_sales = np.nansum(sales_with_missing, axis=1)
total_profit = np.sum(profit, axis=1)

profit_margin = (total_profit / total_sales) * 100

two_decimal = np.round(profit_margin, 2)
nearest_whole = np.round(profit_margin)
floor_values = np.floor(profit_margin)
ceiling_values = np.ceil(profit_margin)

print("Two Decimal Places:")
print(two_decimal)

print("Nearest Whole Number:")
print(nearest_whole)

print("Floor Values:")
print(floor_values)

print("Ceiling Values:")
print(ceiling_values)

Two Decimal Places:
[84.95 84.89 74.03 89.39 81.72]
Nearest Whole Number:
[85. 85. 74. 89. 82.]
Floor Values:
[84. 84. 74. 89. 81.]
Ceiling Values:
[85. 85. 75. 90. 82.]


Question 120: Save and Load Data
Save the following arrays as NumPy binary files:

sales_data.npy
cost_data.npy
profit_data.npy
Load them back and verify that the loaded arrays are equal to the original arrays.

In [27]:
import numpy as np

# Save arrays
np.save("sales_data.npy", sales_with_missing)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit)

# Load arrays
loaded_sales = np.load("sales_data.npy")
loaded_cost = np.load("cost_data.npy")
loaded_profit = np.load("profit_data.npy")

# Verify equality
print("Sales equal:", np.array_equal(sales_with_missing, loaded_sales, equal_nan=True))
print("Cost equal:", np.array_equal(cost_data, loaded_cost))
print("Profit equal:", np.array_equal(profit, loaded_profit))

Sales equal: True
Cost equal: True
Profit equal: True
